version: '3.8'

services:
  llm-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - MODEL_ID=mistralai/Mistral-7B-v0.1
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vector-db:
    image: chromadb/chroma:0.4.18
    ports:
      - "8080:8080"
    volumes:
      - ./vector_db/data:/chroma/data
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSIST_DIRECTORY=/chroma/data

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend
    depends_on:
      - llm-service

  locust:
    image: locustio/locust:2.18.0
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/home/locust
    command: -f /home/locust/locustfile.py --host http://llm-service:8000 