version: '3.8'

services:
  vector-db:
    image: chromadb/chroma:0.4.18
    ports:
      - "8080:8080"
    volumes:
      - ./vector_db/data:/chroma/data
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSIST_DIRECTORY=/chroma/data

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - vector-db 