apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-chatbot

resources:
  - ../../base

patches:
  - path: patches/replicas-patch.yaml
  - path: patches/resources-patch.yaml

configMapGenerator:
  - name: prod-config
    literals:
      - ENVIRONMENT=production

vars:
  - name: LLM_SERVICE_IMAGE
    objref:
      kind: Deployment
      name: llm-service
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.containers[0].image
  - name: FRONTEND_IMAGE
    objref:
      kind: Deployment
      name: frontend
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.containers[0].image

images:
  - name: ${LLM_SERVICE_IMAGE}
    newName: rag-chatbot/llm-service
    newTag: prod
  - name: ${FRONTEND_IMAGE}
    newName: rag-chatbot/frontend
    newTag: prod 