apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rag-chatbot
spec:
  replicas: 5 