apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: llm-service
        resources:
          limits:
            nvidia.com/gpu: 2
            memory: "32Gi"
            cpu: "16"
          requests:
            memory: "16Gi"
            cpu: "8"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m" 