apiVersion: v1
kind: Namespace
metadata:
  name: rag-chatbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rag-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rag-chatbot/frontend:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://localhost:30800"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
      - name: llm-service
        image: rag-chatbot/llm-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: USE_CPU
          value: "true"
        - name: VECTOR_DB_HOST
          value: "vector-db"
        - name: VECTOR_DB_PORT
          value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-db
  namespace: rag-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-db
  template:
    metadata:
      labels:
        app: vector-db
    spec:
      containers:
      - name: vector-db
        image: chromadb/chroma:0.4.15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: rag-chatbot
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
  selector:
    app: llm-service
---
apiVersion: v1
kind: Service
metadata:
  name: vector-db
  namespace: rag-chatbot
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: vector-db 