apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: rag-chatbot/frontend:dev
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: llm-service
        image: rag-chatbot/llm-service:dev
        imagePullPolicy: Never
        env:
        - name: PYTHONPATH
          value: "/app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-db
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: vector-db
        image: chromadb/chroma:0.4.18
        imagePullPolicy: IfNotPresent 