apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: llm-service
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        # Use CPU-based model loading for local development
        env:
        - name: USE_CPU
          value: "true"
      # Remove GPU node selector for local development
      nodeSelector: null 