apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: rag-chatbot
spec:
  template:
    spec:
      containers:
      - name: llm-service
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: null
          requests:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: null
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: USE_CPU
          value: "true"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        command: ["python", "-m", "app.api.main_local"]
      nodeSelector: null 