apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - llm-service-deployment.yaml
  - llm-service-service.yaml
  - vector-db-deployment.yaml
  - vector-db-service.yaml
  - vector-db-pvc.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml 