apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-db-pvc
  namespace: rag-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 